[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./addresses" }]
remappings = ['@openzeppelin=lib/openzeppelin-contracts']

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
